version: '3.8'
services:
  jenkins:
    container_name: jenkins
    image: dajucastro/jenkins:2.420-jdk11
    restart: always
    privileged: true
    user: root
    environment:
      - TZ="America/Bogota"
    ports:
      - 81:8080
      - 50001:50000
    volumes:
      - "../../data/jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
