version: '2'
services:
  mitmproxy:
    container_name: mitmproxy
    image: mitmproxy/mitmproxy
    network_mode: "host"
    extra_hosts:
    - "db-host-occiauto:${DOCKER_MACHINE_IP}"
    - "elasticsearch-host:${DOCKER_MACHINE_IP}"
    - "redis-host:${DOCKER_MACHINE_IP}"
    - "db-host-bc:${DOCKER_MACHINE_IP}"
    - "bc-host:127.0.0.1"
    - "default:127.0.0.1"
    restart: always
    command: mitmweb --web-host 0.0.0.0 --web-port 8081 -s /data/scripts/redirect.py -s /data/scripts/modify_response.py
    environment:
      - APP_PATH=/usr/share/projects/bocc-commons-frontend-ejecutivo-empoderado
      - TZ="America/Bogota"
      - SSH_PORT=41
    volumes:
      - "$(pwd):/data"
    ports:
      - "8080:8080"
      - "8081:8081"
