version: '2'
services:
  proxy:
    container_name: proxy
    image: dajucastro/mitmproxy:9.0.1
#    network_mode: "host"
    extra_hosts:
    - "bc-host:127.0.0.1"
    - "default:127.0.0.1"
    restart: always
    command: mitmweb --ssl-insecure --set client_certs=/data/ssl/client_certs  --web-host 0.0.0.0 --web-port 8081 -s /data/scripts/redirect.py --no-http2 -s /data/scripts/modify_response.py
    environment:
      - TZ="America/Bogota"
      - SSH_PORT=41
    volumes:
      - "./data/proxy:/data"
    ports:
      - 8080:8080
      - 8081:8081

  castlemock:
    container_name: castlemock
    image: dajucastro/castlemock:1.51
    restart: always
    links:
      - "proxy:proxy"
    volumes:
      - "./data/castlemock:/root/.castlemock"
    ports:
      - 80:8080
