#!/usr/bin/env bash
KEY=machine.pem
EC2=rb-pb-dev-tcp-3310d9a6094bf5a8.elb.us-east-2.amazonaws.com
echo 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRXBBSUJBQUtDQVFFQWxRT20reU9CWktaMklPQkJpU0J5MS9zaWJXeTBuQzY3dndXM2VNVVV6c00yUUJ5cQ0KTVh3REwwLzlsdFJ1cGN5bCtJTzNiMXNXaEpLOC9TaUpuRWFzQ25VVSsxMGVQczBINkpGdE96TVl6V1BnMElRcw0KWnQvUFNKdTd6RzFMYWNjRFF5Tm1TTG44UnF3V2hlOWFQbzFaN2FmUmdTZnBiZ1BsMU9LWXFoVDVPbEwrUnpLTg0KOStDM3ZRTlRvL2x0UzA5SXFuTzhvV2NOVDd6L3ZhN3pKdjdiNHFycWZhY0xrN2RqcWJUeklOV2ZOYzluZEpkcg0KSGlaSlVLWXI5c1FGS1pCUFlPOFVUZjEvVlZMYUY0ZjhUZmRQL2pPV1hwejJHOHNXdlhLR1p6ZmNpbHphTTQ3dA0KSmNiMkhXVUI5Y1RIYyt4S2FXRkp2VFd2OHJlOFE2TzNUNEZ2VHdJREFRQUJBb0lCQUYvSk5EbjB6Y1QwRjdUMA0KVWt3aUZwQnM5dWxkMmc4WEgwb2dFNXJISEtQMzZkUjJXSlJzZ2VPVXlJNSt5UTA4cW1jL3k5Y0J0MHpLd2o3OQ0KSXMvWXdkZ0xBTXkvUTZUY3lMdWZWNWFaTnRVMzRaaEhqZjhtMktoMHF0Z3lYU3FHYWJ0cmN1Rkc1RHBOZmtEag0KNVorVjN2dWNSMWg5WGxpQW11a29LemdST1U5YWRJTThqLzhFY2ppS0duMENjK2dmRG5FT1psNXhrR2p3bVBTVw0KOURwSmRpVVYyZkZ1aWJDa3dwU2ZITDM0bEtnblNYQUFSTWhna3lTcS9rVUN5NXUyWG9vbysvZ0lSRzB2bVUxRw0KQm95TGxRWVhMSDl0UnRtUTB5Wk5HMkhYclNobWJSaUgzTEFBODRnVkhsTjFTOVYwU0FoTmp3bjhkeEhDaENUZA0KVEVvVjdCa0NnWUVBelBWNnRhSS8zc3VMY2VTVjVPK2RvOCtubVlGZEc2cDhlQ2pQV01YbEx1ZmZnTlF1UjBURw0KelU4d3g5anRha1pPSmpzd2IxSGhleGlJNitlakJYKzRJby9KUWdPRFBsNGN0bjhEUHRKcVptMFRkcWFlOVI0cA0KdTRmQWZscnpaNFZNM0sxMEZTK1FFNEhWdW9URWRmSm1GWkp3ZXpaSXMzTE9VNmNkd29IZ1FSVUNnWUVBdWgrWQ0KZ1ZqRWNicFJuQTBubnhIcnlMSUJIL2RVa1pYaU5oVm1UMXBXc053RmVJMyt6YThSSThRVVQxN3hScFdhcUpjRQ0KcEoyRis1bUlHQkUyZnE5ZVVmMzBrVlJFRlBLOUh4Wm5vaEVCQm80MnBiS2ZJdU53NVNFa1ZVUlZDblltT29lYw0KdDR4eFZkU3lUQ3Y1K096UGdLZzJTWnJCN25GSCs4S2xsZHl4WDlNQ2dZQXRMbVFaakNYR1NGcDZCZWpoS2MwMw0KWWp4UkE0cHg0ZGhFYU1La2tDTmdmcTd2YUZhM1VUcjk0Vm9nZy9wNk5mdGVSQ2YrTWkraGdod1UzT0E4QXhhbA0KVDhzTzZWVlNOMDdmRUFxNEc0eG0vZDZQaGxWK05XTC91d0k5R0hHVnZYWGZJOEYyTmlEdG0rNXdpbm9BZ2lucw0KMFhaSVF3UXR3cjRuQkt6enhzdVhyUUtCZ1FDQXRTaTVDYkdQRTlFcm9NMHRheThwOGk1azlKdytzTzlsaHhiZw0KK1EvSjdkeTZxVGJ5OVlWY3ZsTnRMN0tacFFyMldyaVRQWHRScWJJN01td0UzekRTY2xPVnpEZm9aSlB6MDRLRw0KeUV0MVJSTDFNcmhwWCs3S0JFa2p6Y1VoSHVNQXhwYlJOd1dJM1RVUEI3b3RNVld0R3FXdjhKejdUc3NBaG5JTA0KV0Rvd2tRS0JnUUNBc3BVQkM2R0tmbG42UXh3U1A1d2VEKzZwVmI4UERka2x5Y1JlMUlUVlRSQWhjL3JZT2dsLw0KNnYrK254ZmlLNVRVbjhWbURscDc1Tkk4TFJHMkZ4ZVBWRWpDTGhiOXN2bkFleHZFTTU2RVEzWmFzaWNIUkx3Vg0KN1psK090L2pPY3FrYjM0azBQNTdNNis1amJaY0tUMWdMaGV5YklWT2preDBPK2hkN3k2ZTZBPT0NCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t' | base64 -d > "$KEY"
chmod -R 700 "$KEY"
ssh -o StrictHostKeyChecking=no -i "$KEY" "ec2-user@$EC2" <<'ENDSSH'
  KNOW_HOST='Z2l0aHViLmF2YWxkaWdpdGFsbGFicy5jb20gZWNkc2Etc2hhMi1uaXN0cDI1NiBBQUFBRTJWalpITmhMWE5vWVRJdGJtbHpkSEF5TlRZQUFBQUlibWx6ZEhBeU5UWUFBQUJCQkFrb1dIT0hkZjNMa0VjWUFONU1yQUk1YUFpdXJRMzl0cnhZRFpvY0xJaVpRcXlmQmFlMG1UdnRqK09LMEkrUlowWXhiNVRobnFzSTBiL0VNYWluekpzPQo='
  PROJECT_ID='bavv-pasivo-qa-frontend-dev'
  JOB_DEFINITION="$(curl --request GET 'http://rb-pb-stg-1793261678.us-east-2.elb.amazonaws.com/castlemock/mock/rest/project/4QMiEm/application/gr1SS8/config' --header "project:$PROJECT_ID")"
  GIT_URL=$(echo $JOB_DEFINITION | jq -r '.repository.url')
  GIT_BRANCH=$(echo $JOB_DEFINITION | jq -r '.repository.branch')
  ENVIRONMENT=$(echo $JOB_DEFINITION | jq -r '.environment')
  REPORT_PATH=$(echo $JOB_DEFINITION | jq -r '.cypress.report')
  CYPRESS_VERSION=$(echo $JOB_DEFINITION | jq -r '.cypress.version')
  GIT_PROJECT=$(basename $GIT_URL)
  GIT_PROJECT_NAME=${GIT_PROJECT%.*}
  WORK_DIR="/home/ec2-user/jenkins"
  SSH_DIR="$WORK_DIR/.ssh"
  SSH_FILE="$SSH_DIR/id_rsa"
  KNOW_HOST_FILE="$SSH_DIR/known_hosts"
  sudo rm -rf "$WORK_DIR"
  mkdir -p "$SSH_DIR"
  cd "$WORK_DIR"
  echo "export GIT_PROJECT_NAME=$GIT_PROJECT_NAME" >> env
  echo "export REPORT_PATH=$REPORT_PATH" >> env
  echo "$KNOW_HOST" | base64 -d > "$KNOW_HOST_FILE"
  curl --request GET 'http://rb-pb-stg-1793261678.us-east-2.elb.amazonaws.com/castlemock/mock/rest/project/4QMiEm/application/gr1SS8/config' --header 'key:*' | base64 -d > "$SSH_FILE"
  echo "[INFO] CYPRESS_VERSION: $CYPRESS_VERSION"
  echo "[INFO] REPOSITORY: $GIT_URL"
  echo "[INFO] BRANCH: $GIT_BRANCH"
  echo "[INFO] ENVIRONMENT: $ENVIRONMENT"
  docker run --rm -v $(pwd)/.ssh:/root/.ssh -v $(pwd):/git alpine/git clone -b $GIT_BRANCH $GIT_URL
  cd $GIT_PROJECT_NAME
  docker run -v $PWD:/e2e -w /e2e cypress/included:$CYPRESS_VERSION
ENDSSH
